server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.16.200:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # thymeleaf模板相关配置
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    mode: LEGACYHTML5