spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: ninomer-application
  profiles:
    include:
      - dev
      - dev-project
  server:
    max-http-header-size: 8192
mybatis:
  mapper-locations: classpath*:**/xml/*Mapper.xml